"""empty message

Revision ID: 075df29b0790
Revises: a5cffa318ac2
Create Date: 2025-12-11 20:49:18.680097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075df29b0790'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('color_de_ojos', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planeta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('clima', sa.String(), nullable=False),
    sa.Column('diametro', sa.Integer(), nullable=False),
    sa.Column('terreno', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('fecha_de_subscripcion', sa.Integer(), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha_de_subscripcion')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    op.drop_table('planeta')
    op.drop_table('personaje')
    op.drop_table('favorito')
    # ### end Alembic commands ###
